project_id = "ouxjigeaecbpzzrldsdq"

[functions.google-drive-auth]
verify_jwt = false

[functions.google-drive-callback]
verify_jwt = false

[functions.google-drive-export]
verify_jwt = false

[functions.google-drive-verify]
verify_jwt = false